################
### MONITORS ###
################

# source from nwg displays
source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/workspaces.conf

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = , preferred, auto, 1

# laptop monitor
# monitor = eDP-1, 1920x1080@60.05,0x0, 1.0

# hdmi mirror laptop
# monitor = HDMI-A-2, preferred, auto, 1, mirror, eDP-1

# hdmi extended right of laptop
# monitor = eDP-1, preferred, 0x0, 1
# monitor = HDMI-A-2, preferred, 1920x0, 1

